### ISSUE TITLE
registry.Stop() drops metrics if all retries fail

### ISSUE THREAD

**Issue by hankjacobs** [Netflix/spectator-go#48]
Hello,

When calling `registry.Stop()`, metrics may be dropped if all retries fail. Off the cuff, one solution is to expose a `.Flush()` method on the registry that flushes metrics to the Atlas backend and returns an error if it fails to do so. By doing this, callers can manually retry before calling `.Stop()` and exiting.

**Comment by copperlight** [comment]
The current configuration provides for three retries with a linear backoff (100ms, 200ms, 300ms). It will log messages relevant to the errors encountered and it will increment a `name=spectator.measurements,id=dropped,error=http-error` metric.

If an instance is failing three consecutive retries, then there may be a larger issue going on which cannot be solved by making more attempts.

Adding a `.Flush()` method complicates the usage of this library - it duplicates what the `publish()` method does on a regular schedule, but at an arbitrary time, and the registry still needs to be stopped anyway.

**Comment by copperlight** [comment]
Now that spectator-go is a thin client, there is no longer a full-fledged Registry which requires stopping.
